package com.hospital;

public enum Illness {
  DIABETES, HYPERTENSION, INFLUENZA, ASTHMA, ARTHRITIS, ALZHEIMERS, PNEUMONIA, OSTEOPOROSIS, TUBERCULOSIS, CHOLERA,
  MALARIA, ANEMIA, BRONCHITIS, HEPATITIS;

}
